version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - translation-network

  nginx:
    image: nginx:alpine
    container_name: translation-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - translation-network

  mysql:
    image: mysql:8.0
    container_name: translation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - translation-network

  redis:
    image: redis:alpine
    container_name: translation-redis
    restart: unless-stopped
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge

volumes:
  dbdata: 